#!/usr/bin/env python3
"""Stitch the base together: cross-document links become local paths.

A second pass, run after import. It reads the frontmatter of every converted
document, builds a ``page id -> file name`` registry, and rewrites links::

    [Billing rules](https://wiki.example.com/pages/viewpage.action?pageId=42)
    -> [Billing rules](billing.md)

A separate pass on purpose: a newly added document has to repair links inside
the documents that already existed.

Idempotent. Links that are already local are left alone; links to pages that
have not been imported yet stay absolute and are reported as missing.
"""
import argparse
import json
import os
import re
import sys
from urllib.parse import unquote

SOURCES = "kb/sources"
LINKMAP = "kb/linkmap.json"
GRAPH = "kb/graph.md"

RE_FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n", re.S)
from . import frontmatter
RE_TITLE = re.compile(r"^#\s+(?:\[)?(.+?)(?:\]\(|$)", re.M)
RE_MD_LINK = re.compile(r"\[([^\]]*)\]\(([^)\s]+)\)")
PAGE_ID_TAIL = r"/.*?(?:/pages/(\d+)/|[?&]pageId=(\d+))"


def page_pattern(internal_hosts):
    """Match wiki page URLs on any of the configured hosts."""
    if not internal_hosts:
        return re.compile(r"(?:/pages/(\d+)/|[?&]pageId=(\d+))")
    hosts = "|".join(re.escape(h) for h in internal_hosts)
    return re.compile(f"(?:{hosts})" + PAGE_ID_TAIL)


RE_CONF_PAGE = page_pattern(())
RE_ANCHOR = re.compile(r"#(.+)$")


def page_id_of(url, pattern=None):
    m = (pattern or RE_CONF_PAGE).search(url)
    return (m.group(1) or m.group(2)) if m else None


def scan(sources_dir):
    """{page_id: {file, title}} gathered from every document's frontmatter."""
    registry = {}
    for name in sorted(os.listdir(sources_dir)):
        if not name.endswith(".md") or name.startswith("_"):
            continue
        text = open(os.path.join(sources_dir, name), encoding="utf-8").read()
        fm = RE_FRONTMATTER.match(text)
        if not fm:
            continue
        pid = frontmatter.read_id(fm.group(1))
        if not pid:
            continue
        title = RE_TITLE.search(text)
        registry[pid] = {
            "file": name,
            "title": title.group(1).strip() if title else name,
        }
    return registry


def relink(text, self_id, registry, stats, pattern=None):
    """Rewrite the links inside one document."""
    def repl(m):
        label, url = m.group(1), m.group(2)
        pid = page_id_of(url, pattern)
        if not pid:
            return m.group(0)                       # not a wiki page link
        if pid == self_id:
            stats["self"] += 1
            return label                            # self-link: drop the link
        target = registry.get(pid)
        if not target:
            stats["missing"].setdefault(pid, set()).add(label[:60])
            return m.group(0)                       # not imported yet: keep the URL
        anchor = RE_ANCHOR.search(unquote(url))
        hint = ""
        if anchor:
            frag = re.sub(r"[:~].*$", "", anchor.group(1)).replace("id-", "")
            frag = re.sub(r"[^\w\s-]", " ", frag, flags=re.UNICODE).strip()
            if frag:
                hint = f' "{frag[:60]}"'
        stats["linked"] += 1
        stats["edges"].add((self_id, pid))
        return f"[{label}]({target['file']}{hint})"

    return RE_MD_LINK.sub(repl, text)


def run(sources=SOURCES, check=False, quiet=False, internal_hosts=(),
        open_url=None, linkmap_path=None, graph_path=None):
    """Rewrite cross-document links and regenerate the map.

    Output paths are explicit: resolving them against the current working
    directory only works when the caller happens to stand in the base root.
    """
    linkmap_path = linkmap_path or LINKMAP
    graph_path = graph_path or GRAPH
    # Passed down rather than stashed in a module global: two calls with
    # different hosts in one process would otherwise interfere, and a
    # long-running server is exactly such a process.
    pattern = page_pattern(internal_hosts)
    host = internal_hosts[0] if internal_hosts else ""
    if open_url is None:
        def open_url(pid):
            return (f"https://{host}/pages/viewpage.action?pageId={pid}"
                    if host else f"(page id {pid})")

    class _A: pass
    args = _A(); args.sources = sources; args.check = check

    registry = scan(args.sources)
    stats = {"linked": 0, "self": 0, "missing": {}, "edges": set()}
    if not registry:
        return registry, stats          # an empty base is a state, not an error
    for pid, info in registry.items():
        path = os.path.join(args.sources, info["file"])
        text = open(path, encoding="utf-8").read()
        new = relink(text, pid, registry, stats, pattern)
        if new != text and not args.check:
            open(path, "w", encoding="utf-8").write(new)

    # linkmap.json is derived; it is never edited by hand.
    linkmap = {
        "_comment": "Generated by docbase. Do not edit by hand.",
        "by_page_id": {
            pid: f"{args.sources}/{i['file']}" for pid, i in sorted(registry.items())
        },
        "missing": {
            pid: sorted(labels)
            for pid, labels in sorted(stats["missing"].items())
        },
    }
    if not args.check:
        os.makedirs(os.path.dirname(os.path.abspath(linkmap_path)), exist_ok=True)
        with open(linkmap_path, "w", encoding="utf-8") as handle:
            json.dump(linkmap, handle, ensure_ascii=False, indent=2)

    # graph.md is the human- and agent-readable map of the base.
    lines = ["# Base map", "",
             "Generated by `docbase map`. Shows which documents exist and what",
             "they reference.", "", "## Imported", "",
             "| page id | Document | File |", "|---|---|---|"]
    for pid, i in sorted(registry.items(), key=lambda kv: kv[1]["file"]):
        lines.append(f"| `{pid}` | {i['title']} | [{i['file']}](sources/{i['file']}) |")

    lines += ["", "## Referenced but not imported yet", ""]
    if stats["missing"]:
        lines += ["| page id | Referred to as | Open |", "|---|---|---|"]
        for pid, labels in sorted(stats["missing"].items()):
            label = "; ".join(sorted(labels)[:3]).replace("|", "/") or "—"
            lines.append(f"| `{pid}` | {label} | "
                         f"{open_url(pid)} |")
    else:
        lines.append("Everything referenced is already available locally.")

    if stats["edges"]:
        lines += ["", "## Reference graph", "", "```mermaid", "graph LR"]
        for a, b in sorted(stats["edges"]):
            lines.append(f'  {a}["{registry[a]["file"]}"] --> {b}["{registry[b]["file"]}"]')
        lines.append("```")
    lines.append("")

    if not args.check:
        os.makedirs(os.path.dirname(os.path.abspath(graph_path)), exist_ok=True)
        with open(graph_path, "w", encoding="utf-8") as handle:
            handle.write("\n".join(lines))

    if not quiet:
        mode = "checked" if args.check else "written"
        print(f"[{mode}] documents: {len(registry)}  "
              f"links localized: {stats['linked']}  "
              f"self-links dropped: {stats['self']}  "
              f"pages not imported: {len(stats['missing'])}", file=sys.stderr)
        for pid, labels in sorted(stats["missing"].items()):
            print(f"  ! {pid}  {'; '.join(sorted(labels)[:2])}", file=sys.stderr)
    return registry, stats


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sources", default=SOURCES)
    ap.add_argument("--check", action="store_true", help="report only, change nothing")
    args = ap.parse_args()
    registry, _ = run(sources=args.sources, check=args.check)
    if not registry:
        raise SystemExit(f"no documents found in {args.sources}")


if __name__ == "__main__":
    main()
